version: "2"

networks:
  retropoker:

volumes:
  mongodb:

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - retropoker